version: '3'
services:
  nginx:
    build: .
    restart: unless-stopped
    volumes:
      - ./crontab:/var/spool/cron/crontabs/root
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Shanghai
    command: >
      sh -c "crond &&
             nginx -g 'daemon off;'"