version: '2'
services:
  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log:/var/log/nginx
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Asia/Shanghai
    command: sh -c "apk add --no-cache tzdata && nginx -g 'daemon off;'"